### ISSUE TITLE
Accessing unknown VxD 33b6

### ISSUE THREAD

**Issue by lab313ru** [otya128/winevdm#1005]
```
version: 2119
4cd0:err:int:DOSVM_Int2fHandler 334: int2f: unknown/not implemented parameters:
int2f: AX 4010, BX 0005, CX 000f, DX 0800, SI 0068, DI 0000, DS 164f, ES 164f
4cd0:err:int:do_int2f_16 411: Accessing unknown VxD 33b6 - Expect a failure now.
4cd0:err:int:DOSVM_Int2fHandler 334: int2f: unknown/not implemented parameters:
int2f: AX 4010, BX 0005, CX 000f, DX 0800, SI 0068, DI 0000, DS 166f, ES 166f
4cd0:err:int:do_int2f_16 411: Accessing unknown VxD 33b6 - Expect a failure now.
```

**Comment by cracyc** [comment]
Need more info about the program and a trace.

**Comment by cracyc** [comment]
It seems that vxd 33b6 is sentinel.vxd which is a driver for a parallel port copy protection dongle.  It might be possible to make it work with some effort but you'd need to have the actual dongle it have any hope of implementing it.  Otherwise you'd need to find a crack if one exists for your program.

**Comment by lab313ru** [comment]
You right, it's a copy protection. Now I can't even make it fail...
