### ISSUE TITLE
Slam! - Graphical glitches when puck/players are in fast movement

### ISSUE THREAD

**Issue by mskrzynski** [otya128/winevdm#1101]
Slam! works fine but the graphics seem to be glitching where parts of the puck and players go missing while in fast movement. You can see it in the video I've recorded here: https://streamable.com/ebtzrx

It should be solid all the time.
I am using latest version - otvdm-master-2246.

**Comment by cracyc** [comment]
I don't see this, it might be a video driver/dwm issue.  What display adapter do you have?

**Comment by mskrzynski** [comment]
Compare this to how it looks on other videos like here: 
https://youtu.be/RIgQrWYQX_E?t=14 
https://youtu.be/CHp6SGm0-Os?t=149

I have AMD Radeon R7 265, but I've noticed the same thing using GeForce drivers with RTX 2060/GTX 660.

**Comment by cracyc** [comment]
Since I can't repo it I really can't debug it.  The program uses GDI primitive calls for everything so it's highly likely the problem is in the GDI or below not in winevdm.  I believe that the GDI is single buffered so the problem could be with the display driver or dwm not syncing to vblank and thus causing tearing.

**Comment by ArguaBILL** [comment]
I have a completely different issue with this game, and that is that the samples you can hear in mskrzynski's provided video aren't playing (and yes I do have the sound option enabled)

**Comment by otya128** [comment]
Tearing is also occurring in that video
![1](https://user-images.githubusercontent.com/4075988/150295587-7f75d536-b5a5-4019-8508-74e2002c028b.png)
![2](https://user-images.githubusercontent.com/4075988/150295590-0be0232a-417a-4b87-ab36-6dc06a0c29ef.png)
.

**Comment by ArguaBILL** [comment]
The ultimate test would be to build a genuine Windows 3.11 machine with a decent video card (one of those "Windows accelerators" or something.)

Also, I have reason to believe that the screen tearing could be caused by that guy's VGA capture device as there's some light tearing in his WinTrek video too

**Comment by mskrzynski** [comment]
Using the latest version at the time of writing this (otvdm-master-2411) and with changes to the hardware since the issue was created (Radeon RX 6600, Acer K243Y monitor 75Hz with Freesync, updating to Windows 11) I tested it again and the issue seems to be resolved, both the blue players and the purple puck are rendered fully (not in chunks like in the video) as intended.
