### ISSUE TITLE
"Unable to allocate dialog trunk" when playing Civilization I

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#122]
This happens roughly mid-game so I suppose this is a manifestation of memory shortage.

**Comment by cracyc** [comment]
Civ 1 creates tons of dialogs and it'll likely run out of thunk space over a long session.  It seems to me that line 648 of dialog.c should not check thunk_array[i].used because used is never cleared anywhere and IsWindow will check is the dialog actually still exists (plus used is already checked in the previous loop).

**Comment by cracyc** [comment]
Civ 1 creates lots of dialogs so it'll likely run out of thunk space in a long session.  Allocate_proc_thunk looks for unused thunks but the second loop checks that .used is not set again which means if a dialog is created and destroyed it's thunk will never get reused as .used is never cleared.
