### ISSUE TITLE
Microsoft 500 Nations closes on launch and while running as admin, the Win16 version hangs while the Win32 version runs fine

### ISSUE THREAD

**Issue by CSmeds99** [otya128/winevdm#1276]
While launching Microsoft 500 Nations normally, the program closes upon launching. When running with otvdmw.exe as administrator, the Win16 version hangs with the Microsoft Home splash screen. while the Win32 version runs normally. The Win16 version has to be manually terminated to close, while the Win32 version  can be closed normally. The Windows version is set to 3.95 in otvdm.ini.

The program needs to be run under admin under Windows 10 (x86) NTVDM but only the Win32 version runs normally, while the Win16 version is not launched.

![500 Nations 2](https://user-images.githubusercontent.com/99499673/223171821-9e30a276-90a3-48fd-b192-63e4099b28ae.png)
![500 Nations 1](https://user-images.githubusercontent.com/99499673/223171828-ca90fb93-c76d-4451-a633-eb6d1d5e1bdb.png)

Windows 11 Pro 22H2 OS build 22621.1265
 WineVDM build 2413

Note: The trace file doesn't give any detailed information, and just the WineVDM build version.

[trace.txt](https://github.com/otya128/winevdm/files/10900775/trace.txt)

**Comment by CSmeds99** [comment]
Updated trace:

[trace.txt](https://github.com/otya128/winevdm/files/10900717/trace.txt)

**Comment by cracyc** [comment]
If you run it directly with "Nations\_Setup\App\Explor16.exe Nation16.dll /w Nations\_Setup\App\WavOut16.dll nations.the" from the root of the cdrom drive does it work then?

**Comment by CSmeds99** [comment]
> 

The Win16 version runs fine without the Microsoft Home logo in the beginning. When I switched "16" to "32" in the path, the Win32 version runs fine, without the Microsoft Home logo in the beginning.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1281 gets the win16 version starting from nations.exe but WINVER=3.1 and IAmNotNT=1 in otvdm.ini.  Otherwise it loads the win32 version but only if it can write a registry entry into HKEY_LOCAL_MACHINE which requires elevation (it uses registry functions in kernel32 so aren't easily redirectable).

**Comment by cracyc** [comment]
Do you mean the window with the mshome logo?  That's not the win16 version, that's part of nations.exe (which is a 16bit program).

**Comment by CSmeds99** [comment]
> Do you mean the window with the mshome logo? That's not the win16 version, that's part of nations.exe (which is a 16bit program).

Yes

**Comment by CSmeds99** [comment]
Yes

**Comment by cracyc** [comment]
It's not closing the mshome window because it uses findwindow with the window class to locate it.  Since winevdm mangles window class names, the main program can't find it.  This would be very difficult to fix so I think the best options are either to run the win16 version using the otvdm.ini settings or run the win32 version directly using the command line above (with 32 like you said).
