### ISSUE TITLE
Excel demo crashes

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#13]
This is the version 2.1p working model.  Since it can be distributed I'm attaching it.  Since I saw the changes regarding version 2 compatibility I thought this may help.

[xldemo.log](https://github.com/otya128/winevdm/files/2287568/xldemo.log)
[xldemo.zip](https://github.com/otya128/winevdm/files/2287573/xldemo.zip)

the zip password is winevdm

**Comment by neozeed** [comment]
I just tried Excel 2.1d which works in Windows 3.0 386 Enhanced mode..  Zero pressure as Excel 3.0 works seemingly well enough for my initial tests.

[excel21d_crash.log.gz](https://github.com/otya128/winevdm/files/2292240/excel21d_crash.log.gz)

And for testing, Excel 2.1d password is winevdm
[excel2.zip](https://github.com/otya128/winevdm/files/2292241/excel2.zip)

**Comment by neozeed** [comment]
And Word 1.1a which also runs on Windows 3.0 in 386 Enhanced mode.

[winword11a_crash.log.gz](https://github.com/otya128/winevdm/files/2292257/winword11a_crash.log.gz)

And here is Word 1.1a and as always the password is winevdm
[winword1.zip](https://github.com/otya128/winevdm/files/2292261/winword1.zip)

**Comment by otya128** [comment]
This program looks like "self-load". I found a bug in "self-load" and fixed it.
This issue may be fixed.

**Comment by neozeed** [comment]
The demo still crashes, although I'm sure it may very well be a real-mode only thing.  2.1d however doesn't crash on load but has a tonne of unimplimented stub errors, which means it's loading!

Word 1.1a oddly enough does a "SetSwapAreaSize16 750: (6400)" and errors out saying not enough memory.

Word 2.0 does a bunch of SetSwapAreaSize16  calls but runs fine.    Also it sees 1929972kb free... Maybe it's too much memory?  I have no idea of anyone ever ran Word 2.0 on Windows NT back in 1991 so maybe it had to be made to not freak out over the entire 2GB address space?

Awesome work as always!

**Comment by neozeed** [comment]
![excel 21d on windows 10](https://user-images.githubusercontent.com/9031439/44265542-94616500-a259-11e8-9c7b-ad594a298784.png)

Just tried Excel 2.1d on build ce6e225530a941625a6e75706b56478a9d805ff7

odd results but yeah, it's running!

**Comment by neozeed** [comment]
I went ahead an built 1f168222ad2293a8eecfe3149fdd161c41ab44eb re-setup the registry and set the DOS version to 3.3 and the Windows version to 2.01 and word 1.1a actually loads up now.

It can't load any documents, because apparently there isn't enough memory..
![word v1 1a cant open document](https://user-images.githubusercontent.com/9031439/44323959-8e040080-a486-11e8-8652-edfc36504600.png)

![word v1 1a about after version to 2 xx](https://user-images.githubusercontent.com/9031439/44323963-8fcdc400-a486-11e8-9ea9-ad9db51f63f4.png)

This reminds me of the old issues in MS-DOS where OS/2 2.00 could provide 640KB of available RAM and some programs would error out as it was 'not enough memory' as they never expected as much, so you had to actually decrease available memory...

**Comment by neozeed** [comment]
I should try to build Word 1.1 since it's source is out there... and see if there is something weird in the way it allocates ram.

**Comment by malxau** [comment]
This is nuts.  Word 1.1 calls GetVersion to check the Windows version number.  If it gets 3.x, it tries to load its icon, which fails because Wine isn't supporting Windows 2.x resources.  If it gets 2.x, it doesn't bother trying to load the icon, and goes on its merry way.  Also, if it gets 3.x, it looks in win.ini's [Microsoft Word] section for an int value of "NewLook".  It makes you wonder what was going on there.

I'm curious about the document windows too, but need to stop looking at these logs for the night.  Note Word 1.1 was trying to implement MDI before MDI was really supported, so I'm expecting some serious hackery.

@neozeed I'd mentioned to you before how Word 1.1 won't run on NT 3.1 once any service packs are applied, and I'll bet it's related to support for Windows 2.x icons and failing in the exact same spot.  Note that you can't use Program Manager to change an application icon and point it to winword.exe from Word 1 and get an icon out of it in NT 3.51 et al, but it works in NT 3.1 RTM.

**Comment by malxau** [comment]
That's great! I have a native boot MS-DOS machine (Pentium III), and the instructions look really straightforward.  I'll give this a go too.  Btw, did you notice the copyright date on this build is earlier than the binaries we've been using before?

Also, looking at the source it makes almost no use of the resource compiler, since it has its own dialog engine.  In Win16 the resource compiler is really the final stage linker.  It should be straightforward to swap out the 2.x resource compiler for a 3.0 resource compiler and end up with a binary that also works on Win9x + 32 bit NT + WineVDM.  And it looks like MS were doing exactly that at the time, judging from the "-v n.n  use rc version n.n" in the build scripts.

**Comment by ZaDarkSide** [comment]
Is there a link to the Word 1.1a sources?

**Comment by malxau** [comment]
http://www.computerhistory.org/atchm/microsoft-research-license-agreement-msword-v-1-1a/

**Comment by malxau** [comment]
I had the same experience.  I downloaded trunk yesterday, compiled it, and nothing worked.  Since I hadn't had it work before I didn't know what the problem was, but checking out the 0.5.0 tag and compiling as release worked, so I moved on from there.  The release build still generates PDBs which is what I really needed.  (Btw, I'm also using gas 2.13.90 from 2003.)

**Comment by neozeed** [comment]
@malxau Latest commit a340ecc9f44f10da174b8e1bb23c15ff9fa6cb25 is able to run Word!

**Comment by malxau** [comment]
Oohh, I have it running from the tip of master now too.  It looks like otya128 did all the work a few days back to get "ancient" resources to work, making Word work out of the box! Very cool!  (And note that the last time this worked on real Windows was 25 years ago!)

If you really want to bring winevdm to its knees though, try Visual Basic.  Don't install the custom controls (I did and it hangs on launch with them.)  But it's like a Win16 swiss army knife torture tool, making it really easy to do inane things to the system.

**Comment by neozeed** [comment]
using commit 28dd1385a0cfdb6b9e6a5838c1c038e8c5435e4b Word for Windows 1.1a just works!  I didn't set or change anything, as a matter of fact, my WINDOWS directory is empty!

Awesome!

![word 1 1a under 28dd1385a0cfdb6b9e6a5838c1c038e8c5435e4b](https://user-images.githubusercontent.com/9031439/45566129-52433780-b888-11e8-8d29-c7c20725ab92.JPG)

No more 0KB RAM on the first launch.
