### ISSUE TITLE
Borland C++ 4.5 crashes during debugging

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#1309]
Hello,
in the example "bmpview", which is delivered with BC45, BC crashes during debugging within the diagnostic libraries. It happens, when the constructor of TModule is called. See screenshots and trace.
Best regards, 
Mario

![Bild1](https://github.com/otya128/winevdm/assets/68747203/3a918727-bb8e-4d06-b9ad-b4edfd9edbdd)
![Bild2](https://github.com/otya128/winevdm/assets/68747203/c31b0e09-f10a-4504-99dd-312ff5b11e4b)
[Trace_BC45.zip](https://github.com/otya128/winevdm/files/12232893/Trace_BC45.zip)

**Comment by cracyc** [comment]
```
05f4:Call KERNEL.108: SWITCHSTACKTO(23cf,8d4a,5f46) ret=2387:2a72 ds=23cf
05f4:Ret  KERNEL.108: SWITCHSTACKTO() retval=090a1610 ret=2387:2a72 ds=23cf
05f4:Call KERNEL.109: SWITCHSTACKBACK(0000,d463,2377) ret=2387:2a7f ds=23cf
     AX=014d BX=2c92 CX=0000 DX=290f SI=0000 DI=0001 ES=2387 EFL=00003202
05f4:Ret  KERNEL.109: SWITCHSTACKBACK() retval=none ret=2387:2a7f ds=23cf
     AX=014d BX=2c92 CX=0000 DX=290f SI=0000 DI=0001 ES=2387 EFL=00003202
05f4:Call KERNEL.108: SWITCHSTACKTO(23cf,8d4a,5f46) ret=2387:2aa7 ds=23cf
05f4:Ret  KERNEL.108: SWITCHSTACKTO() retval=090a1610 ret=2387:2aa7 ds=23cf
Limit check at 0x0908a0f3 failed. Segment 288f, limit 000031bf, offset 000031c0
```
It's running the debuggee in the same task as the debugger.  That's a bit sketchy.

**Comment by LegacyFreak** [comment]
The same happens with Windows 2000 but not with Windows 3.11.

**Comment by cracyc** [comment]
Doesn't surprise me that it fails in Windows 2000 as there's quite a few problems here.  For one it uses directedyield which can't work well in NT.  Even worse it uses taskswitch which i've found sometimes tries to change the cs:ip for a task that's blocked in getmessage or waitmessage.  This might be fixable for this specific case by sending the task a message to break it out but if it's in any other win32 api (especially apis that call into the kernel) it's not going to work properly.  Ntvdm will work a bit better since a larger part of wow32 is in 16bit code but when 32bit code is called it'll have much the same problems.  I just don't think that this debugger can be made to work reliably in winevdm.

**Comment by LegacyFreak** [comment]
Ok, thanks for your advice.

**Comment by cracyc** [comment]
Turns out win31 does send a message to wake a task so it's expected to work like that.  https://github.com/otya128/winevdm/pull/1310 works a bit better.

**Comment by LegacyFreak** [comment]
Hallo, 
thanks for the patch, but the error still occurs (see trace).
[Trace_BC45.zip](https://github.com/otya128/winevdm/files/12249339/Trace_BC45.zip)

**Comment by cracyc** [comment]
What did you do exactly to case the crash?  I can now step through TModule::TModule without any hang or crash.

**Comment by cracyc** [comment]
The bug underlying the crash also happens in windows 3.1 for me.  It doesn't crash but the debugger state becomes messed up.  I don't think it's a winevdm bug.

**Comment by LegacyFreak** [comment]
Ok, thanks again for your research.
