### ISSUE TITLE
Win 3.1 program with VXD does not run

### ISSUE THREAD

**Issue by dragonbyte1** [otya128/winevdm#1394]
Hi, I'm trying to run a Win 3.1 program (ChromaZone 1995) but it fails with Err msg:
``` ChromaZone is currently compatible only with Version 3.1 of Windows, and can only operate in Windows Enhanced 386 mode.```

The program uses a Virtual Device Driver (chroma.vxd), which I tried in both folders: the executable folder and also in Winevdm Windows\System folder.

What could be done to run the program?

```(Env: Windows 10 Home - 64 bits)```

[trace.zip](https://github.com/otya128/winevdm/files/15012234/trace.zip)
[chroma_vxd.zip](https://github.com/otya128/winevdm/files/15012576/chroma_vxd.zip)

**Comment by cracyc** [comment]
I tried the demo version at https://www.grc.com/chroma.htm and it doesn't have a vxd that it loads although it does use vxd calls to the timer device which are fixed at https://github.com/otya128/winevdm/pull/1395.  It still doesn't work though due to it trying to set the 256 color palette with the video driver directly which will be hard to support properly.
