### ISSUE TITLE
Gazillionaire does not start.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#147]
The game is here: https://archive.org/download/win3_Gaz/win3_Gaz.zip

Says, cannot load some dll.

**Comment by cracyc** [comment]
It loads gsw.exe but winexec returns to early because the thunk lock is released in createwindow.  Some tracing shows releasethunklock is called in message.c:set_app_id.  I'm not sure how to fix it.  If you run gsw.exe then gaz.exe in the same process (by running them from win31 winfile) it then fails because the game has to be in a drive root as it's a cdrom game.  You can use subst.exe to set the path as a drive letter then edit config.gax replacing "A" with the subst drive.  Then it runs.
