### ISSUE TITLE
Cannot Compile Code in uVision/51 for Windows Version 1.32

### ISSUE THREAD

**Issue by SBS-mdasaro** [otya128/winevdm#1471]
**Describe the bug**
The Keil compiler (uVision/51) opens successfully with WineVDM (execute the UVW51.EXE program) but when attempting to run the compiler, it gives an errors that "the return value file could not be read" and does not produce compiled output.

![image](https://github.com/user-attachments/assets/914a5472-170d-461f-b680-4ceeb6154fad)

**Expected behavior**
The program produces a compiled .hex file

**Environment (please complete the following information):**
 - OS: Windows 11 Enterprise 24H2
 - Version 2446

**Additional context**
I have uploaded a copy of the program here: https://www.dropbox.com/scl/fi/4tyvqoj1q639d0bwwsqei/c51.zip?rlkey=60gysucfgsnhdh4m9ida7rwjv&st=f2uju6gt&dl=0

The trace file is also attached
[trace.txt](https://github.com/user-attachments/files/18234052/trace.txt)

**Comment by cracyc** [comment]
There are 2 problems here.  First, 
```
0b10:Call KERNEL.166: WINEXEC(12270cfe "C:\\USERS\\MDASARO\\DESKTOP\\C51\\BIN\\UVWINRUN C:\\Users\\mdasaro\\AppData\\Local\\Temp\\$$WINRUN.$$$ C:\\Users\\mdasaro\\AppData\\Local\\Temp\\$$RUNENV.$$$",0007) ret=11ff:9c88 ds=122f
2ac4:0524:trace:winoldap:WinMain16 1517 14ef "C:\\USERS\\MDASARO\\DESKTOP\\C51\\BIN\\UVWINRUN C:\\Users\\mdasaro\\AppData\\Local\\Temp\\$$WINRUN.$$$ C:\\Users\\mdasaro\\AppData\\Local\\Temp" 7
```
the command line is being cut off because only 128 bytes are available for it.  If you move the program into the root of the drive then there should be enough space.  Second the compiler is a dos program that doesn't work correctly in winevdm's dos emulation.  Open otvdm.ini, get the msdos-player from http://takeda-toshiya.my.coocan.jp/msdos/index.html and put the path where you put it into the "dosemu=" option.  Dosbox may also work but I didn't try it.

**Comment by SBS-mdasaro** [comment]
Thank you so much! This works perfectly. We need to be able to run this old compiler to maintain a couple of very old products. WineVDM is a total lifesaver compared to keeping old hardware running or messing around with a virtual machine.
