### ISSUE TITLE
In Leonard's sketch it is impossible to change font direction

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#177]
https://archive.org/download/MEDLEY_SE120010/SE120010.ZIP

It is impossible to choose the font direction from the pallette, for instance, to put font vertically.

**Comment by cracyc** [comment]
You have to press the Change button to get it to take effect.  There's another bug here though that affects Windows 7 and above (probably Vista too) where text bounding box is not rotated.  It's due to a change in how Get(Tabbed)TextExtent(Point) works with old vector fonts.  In Windows 3.1 - XP it returned the rotated extent but in newer versions it doesn't.
