### ISSUE TITLE
Micrografix Portfolio cannot open sample files

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#187]
http://toastytech.com/guis/Micrografx%20Portfolio%201.0.zip

When picking a sample file from SAMPLES folder via file chooser, it says it cannot find the .PIC file. Second attempt leads to segfault.

**Comment by cracyc** [comment]
The load dialog problem is caused by a WM_ENABLE message sent in EndDialog causes DlgDirSelect to be called after the list box is destroyed.  An empty filename is copied over the selected filename.  If you click the OK button instead of double clicking in the list box, it works.  I'm not sure if all message delivery to dialogs needs to be suppressed after EndDialog is called or what.

**Comment by cracyc** [comment]
The crash is caused by it doing segment arithmetic which doesn't work in protected mode.   I'm not sure if this one can be fixed sanely.   Both problems also affect Micrografix Designer 1.1.
