### ISSUE TITLE
Cabinet from Windows Chicago, build 58 segfaults on start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#195]
First, it complains about lz32.dll, saying it does not have some function. If to remove the dll, cabinet.exe segfaults.

https://winworldpc.com/download/42c2b8c3-90c2-b218-c39a-11c3a4e284a2

Taskman.exe from the same distro also segfaults.

The same happens with sysedit.exe and write.exe

**Comment by cracyc** [comment]
The lz32.dll from that version of chicago uses GetProcAddress16 from kernel32.  That isn't implemented in any version of windows nt-10 and never will be.  The segfault is caused by it failing to import functions from shell.dll which are undocumented, internal exports and are unlikely to ever be implemented.

**Comment by Anixx** [comment]
Mplayer from Plus Pack also segfaults.

**Comment by cracyc** [comment]
Mplayer displays an out of memory message due to a logic error in the program.  Even if it passes that it still crashes due to an implemented export in mmsystem.dll.  Don't expect it to get fixed.

**Comment by Anixx** [comment]
I deleted the lz32.dll and it still segfaults

**Comment by cracyc** [comment]
The segfault is due to the missing undocumented shell.dll exports.
