### ISSUE TITLE
Sound not working in JezzBall and MaxWell's Maniac

### ISSUE THREAD

**Issue by HomerBender77** [otya128/winevdm#378]
For some reason there's no sound in JezzBall and MaxWell's Maniac games from Microsoft Entertainment Pack and the sound option in the options menu is greyed out. And this is despite that the sound files for the programs are in the WEP directory to which I installed the games.

**Comment by cracyc** [comment]
Both work for me.  Would need a trace to try to see what's wrong.

**Comment by AndrewNile** [comment]
I _can_ reproduce this in JezzBall. It has something to do with mmsystem.dll. 

If I copy mmsystem.dll16 into <winevdm_dir>\WINDOWS\SYSTEM and rename it to mmsystem.dll, the menu option works and sound is enabled. Without mmsystem.dll in SYSTEM, it doesn't work.

**Comment by cracyc** [comment]
Try moving mmsystem.dll16 to the same directory as otvdm.exe.  If that works then the dll location logic isn't working properly with LoadLibrary.

**Comment by AndrewNile** [comment]
That's where I normally keep the file, and it doesn't work there. But I had a closer look at JezzBall.

Starting at seg5:0022 it calls GETSYSTEMDIRECTORY, concats it with "\MMSYSTEM.DLL" and tries to open it. 

At seg5:0059 if it fails, it leaves the sub and stops trying to enable sound. Otherwise, it calls LOADLIBRARY with MMSYSTEM.DLL and follows that with a bunch of sound related API calls. 

So WineVDM isn't failing to redirect. Even a dummy MMSYSTEM.DLL in SYSTEM satisfies JezzBall. NTVDM works out of the box because that file exists as part of WOW.

I suppose this checking happens because JezzBall was compatible with Windows 3.0 sans sound system.

**Comment by cracyc** [comment]
The appveyor builds add dummy dlls for that problem but mmsystem was misspelled.  It worked for me because some other installer put a real mmsystem.dll in my fake system dir.  People who make their own builds will have to add the dummy dlls manually.
