### ISSUE TITLE
Indiana Jones desktop adventures crashes on start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#474]

**Comment by cracyc** [comment]
When a program is run from the start menu and opens a console window that window is titled the same as the shortcut.  Since the short cut is "Desktop Adventures" that's what the title is.  When deskadv.exe starts it looks to see if it's already running by searching for a window titled "Desktop Adventures" and exits if found.  To fix this you can rename the shortcut, run deskadv.exe directly from explorer or use otvdmw.exe with ntvdm64 which won't open a console window.

**Comment by Anixx** [comment]
I started the program directly from File Explorer, double-clicking on the .exe.

**Comment by cracyc** [comment]
Works fine here. Will need a trace.

**Comment by jdougharty** [comment]
Crashes for me as well.

**Comment by jdougharty** [comment]
UPDATE: I'm wondering if it has to do with the WAVEMIX.DLL. Upon installing the "preview" version of Indy (which installs its own wavemix.dll) I found it finally runs the full version game fine. It seems I may have had a messed up copy with a messed up wavemix file.

**Comment by cracyc** [comment]
Are you running the latest build?  Whats the version of Desktop Adventures (the one I have is 1.00).  Whats the version of wavemix.dll (the one I have is 1.0.7.0).  Can you make a trace?

**Comment by jdougharty** [comment]
1.00 here. The full version copy was found on an abandonware site and came what looks as preinstalled, which tells me that the program was probably supposed to install a version of wavemix.dll but never did and Indy Desk refused to run without it, so I was using the wavemix.dll from https://www.compuphase.com/wavemix.htm (listed as 1.8). Upon getting a copy of the "preview" installer and running it, I noticed the full version worked fine. Unfortunately, I'm not quite certain how to make a trace. The version of OTVDM was downloaded via Chocolatey (at https://chocolatey.org/packages/winevdm) and according to the site, Version 0.7.0.  
I'm thinking this problem was caused by a faulty copy/installation of Indy Desktop.

**Comment by cracyc** [comment]
The one I have came from the internet archive https://archive.org/download/indianajonesandhisdesktopadventures.  Try that if you can with the latest from appveyor https://ci.appveyor.com/project/otya128/winevdm click on Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1
and then artifacts.

**Comment by Anixx** [comment]
The one you linked works for me.
