### ISSUE TITLE
Programs that "search for installed" compontents seem to freeze(V 1433) 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#487]
Several setup programs that "search for installed components" seem to freeze. One example is "Microsoft Encarta 95", a version of Quicktime had the same problem(but I could skip this step for that setup wizard).

**Comment by jamie-marchant** [comment]
Ok after 30 minutes of "running" the setup for "Encarta 95" otvdmw crashed and was not running a log. Let me know if you want to see one.(and I run it again for 30 minutes)

**Comment by cracyc** [comment]
It searches every directory on the disk which takes a long time on modern machines.  It crashes due to a stack overflow (really a i386 limit overrun).  It's likely a bug in the installer that they never encountered because computers in 1995 didn't have nearly as much storage.  There's probably no simple way to fix this.

**Comment by jamie-marchant** [comment]
Well, you could provide an isolation mode(that can be turned on and off) where 16-bit programs can only see part of your hard disk. (which you can define). Not sure if that is something you guys want to do or not, just puteing my idea out there.

**Comment by anonimuos** [comment]
The trick to use such apps is to install them in a VirtualBox Windows XP VM. Then drag the folders to C:\ drive of your host OS, and the ini to C:\otvdm\Windows. See if the app runs without running Setup - in most cases it does.
