### ISSUE TITLE
Error when trying to install DK Eyewitness Photo Gallery Wild Animals (and probably any other DK title)

### ISSUE THREAD

**Issue by HomerBender77** [otya128/winevdm#493]
During the installation process, this happens:
![bildo](https://user-images.githubusercontent.com/45469534/66097963-8611fd80-e56e-11e9-935c-61f2308c1442.png)

Same with P.B. Bear's Birthday Party.

**Comment by cracyc** [comment]
It tries to write directly to the redirected win.ini but writeprivateprofilestringa returns "Access denied".  Possibly windows sees win.ini in the pathname and "mci extensions" as the section and tries to use the real win.ini which is mostly in the registry while system.ini doesn't have an issue because it writes to the "drivers" section which doesn't exist on x64 windows.  Anyway the error is harmless and can be ignored without issue.

**Comment by WINEVDMbetaTester** [comment]
Copy the DKCODE folder manually to the hard disk.
and in the ini file of the encyclopedia. Modify the following.

[Directory]
Data=d:\

by the letter of the virtual unit in which the iso is mounted.

**Comment by HomerBender77** [comment]
Is the ini file the one called "autorun?"

**Comment by WINEVDMbetaTester** [comment]
the ini file that is inside the DKCODE folder. example

Nature2.ini . Nature Encyclopedia 2. 
vrearth.ini. earth encyclopedia.
space.ini. encyclopedia of the universe
