### ISSUE TITLE
XyWrite for Windows can't find the path to its executable

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#588]
XyWrite for Windows (see an earlier issue) is designed to find its spelling dictionary and other features by looking for its own directory (typically C:\XW) in the DOS path. For reasons that I don't understand, it can't find its own path when running under winevdm, even when I've added C:\XW to the user and system PATH variables.

Is there a fix for this? Again, the installer and an updater are here:

http://www.columbia.edu/~em36/XyWinInstaller.zip

**Comment by cracyc** [comment]
Winevdm doesn't use the host path because it's usually too big and makes some programs mad.  The path is uses is the the combination of the PATH16 envvar and the PATH from the autoexec.bat from the winevdm C dir (or if they don't exist, just the winevdm windows dir).  If you choose for xwrite to put its own dir in the autoexec.bat it should just work.

**Comment by emendelson** [comment]
That works! Thank you!

**Comment by emendelson** [comment]
I know this is closed, but someone else reported that the autoexec.bat in winevdm C didn't solve the path problem, but that setting the PATH16 variable did work. I can't imagine why the autoexec.bat setting works on my system but not the other system, but that seems to be the case. I'm noting this here in case someone else has the same problem.
