### ISSUE TITLE
Uninvited crashes otvdm after playing any sound

### ISSUE THREAD

**Issue by filipetolhuizen** [otya128/winevdm#642]
Playing without sounds works fine, but enabling it, it crashes a few seconds after playing any sound.
Environment:
•OS: Windows 7 64 bits SP1
•Version: dev1685 and earlier builds.

![Uninvited](https://user-images.githubusercontent.com/22864486/76693529-75010880-6645-11ea-90f1-4fe6b79c5644.JPG)
[trace.txt](https://github.com/otya128/winevdm/files/4333684/trace.txt)

**Comment by otya128** [comment]
The tail of trace.txt seems to be missing.
I fixed it so that it would not be missing, so try to trace again with the latest version.

**Comment by filipetolhuizen** [comment]
Updated trace.txt, funny thing is when it's tracing, sound play twice before crashing.
[trace.txt](https://github.com/otya128/winevdm/files/4340903/trace.txt)

**Comment by filipetolhuizen** [comment]
Turns out if I leave another instance of otvdm(w).exe standing by an .exe and run the game, it doesn't crash.

**Comment by filipetolhuizen** [comment]
Here's x32dbg register.
[register.txt](https://github.com/otya128/winevdm/files/4547691/register.txt)

**Comment by cracyc** [comment]
It looks top be crashing while parsing the wav file by reading past the end of the it.  The file might be corrupt.

**Comment by filipetolhuizen** [comment]
That copy also crashes on the same place for me.

**Comment by cracyc** [comment]
I think I know whats happening.  It plays the sound then polls with an empty wav file and SND_NOSTOP waiting for success to indicate completion.  The problem is the empty wav file is smaller than the wav header and when it is played it'll crash depending on what happens to be in the space that the end of the header would fill.  Windows 10 handles the fault so prevents the crash but Windows 7 doesn't.  The trace did show this because it uses SND_ASYNC so the crash is in a different thread.

**Comment by filipetolhuizen** [comment]
Thanks! It's running fine now.
