### ISSUE TITLE
install.inf Not Working for Windows 1 Apps

### ISSUE THREAD

**Issue by techana** [otya128/winevdm#702]
**Describe the bug**
I right-clicked on install.inf and selected "Install", but still can't run programs made for Windows 1 directly from the File Explorer. When I click on a program, e.g. calc.exe, I get a message saying: "This app can't run on your PC"

I can directly run programs for Windows 2 and above though.

**Expected behavior**
I expect executing programs made for Windows 1 when double-clicking on them.

**Environment (please complete the following information):**
 - OS: Windows 10 x64 v.2004
 - Version: otvdm-master-1745

**Comment by cracyc** [comment]
Windows checks the expected os version in the ne header and only excepts 2 or 3 as win16 programs.  Windows 1.0 programs have 0 there so are treated as dos programs and not passed to ntvdm64.dll.  Only microsoft could fix this but since it's been this way since at least windows xp I wouldn't expect them to.

**Comment by techana** [comment]
Thank you for the answer.

I'm sorry to add to this after closing the issue, but I was able to run Windows 1 apps directly by changing their headers (at address 0x43F) from 0x00 to 0x02.

`% printf "\x02" | dd of=CALC.EXE bs=1 seek=0x43f count=1 conv=notrunc`

All apps worked except: CALENDAR.EXE, CARDFILE.EXE and WRITE.EXE.
