### ISSUE TITLE
Error in "A Night To Remember" 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#705]
---------------------------
Interrupt 0D #GP (1517:2580) flags 3206 err FFFC
les     bx,[bp-112h]

---------------------------
address=773E4622
access address=6D83BBEC
VM context
EAX:850000,ECX:0000,EDX:850000,EBX:FFFF
ESP:59BE,EBP:5ADA,ESI:2ADE,EDI:FFFF
ES:19CF,CS:1517,SS:1227,DS:1537,FS:0000,GS:0000
IP:2584, address:6D84AC2D
EFLAGS:00003206

Interrupt 0D #GP (1517:2580) flags 3206 err FFFC
les     bx,[bp-112h]

---------------------------
Cancel   Try Again   Continue   
---------------------------

**Comment by cracyc** [comment]
This isn't enough information, need a trace.

**Comment by jamie-marchant** [comment]
Please remind me how to do this again.

**Comment by cracyc** [comment]
Look in https://github.com/otya128/winevdm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jamie-marchant** [comment]
[trace.txt](https://github.com/otya128/winevdm/files/4794587/trace.txt)

**Comment by cracyc** [comment]
`1778:2078:fixme:mmsys:MMIO_AddThunk 224: Out of mmio-thunks. Bump MMIO_MAX_THUNKS`

Okay, this seems to be opening every movie file on the disk.  It's likely intentional too because it does "SETHANDLECOUNT(00ff)".  I guess try https://ci.appveyor.com/project/otya128/winevdm/builds/33584568/job/dm9dgfs5a7oprfch/artifacts which ups it to 64.

**Comment by jamie-marchant** [comment]
Yes this is fixed in the latest build.
