### ISSUE TITLE
Microsoft SoundBits Media Browser crashes with exception

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#736]
Running the latest OTVDM AppVeyor build as of this bug report.

Microsoft SoundBits (https://winworldpc.com/product/microsoft-soundbits/10) installs fine and the Media Browser app opens but immediately crashes with an exception: https://i.imgur.com/kOdMPjT.png

**Comment by cracyc** [comment]
This one is bad.  It sets a message hook and expects messages that arrive twice to have the same address otherwise it keeps sending the same message between the hook and wndproc until it crashes with a stack overflow.  We convert the 32bit to 16bit messages by making a new MSG struct on the stack which means it has a different address.  It would probably take a significant change in message handling to fix this.

**Comment by anonimuos** [comment]
Fixed. :) Thank you so much for fixing so many app issues so fast.
