### ISSUE TITLE
Microsoft Scenes fails to run

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#738]
Running latest build as of 22 July 2020.

Microsoft Scenes 1.0 and 2.0 fails to run although it installs OK. Any collection from these:
https://winworldpc.com/product/microsoft-scenes/20

If any one of them works, the other will work as the program to manage the sets is common between all. When I start it on Windows 10 64-bit with OTVDM, I get this error:
https://i.imgur.com/GFaUjfU.png

**Comment by cracyc** [comment]
Works for me.  Need a trace to try and debug.

**Comment by anonimuos** [comment]
Here are 2 of them attached:
[trace.txt](https://github.com/otya128/winevdm/files/4958619/trace.txt)

[Trace2.txt](https://github.com/otya128/winevdm/files/4958621/Trace2.txt)

**Comment by cracyc** [comment]
`1ce4:Call KERNEL.129: WRITEPRIVATEPROFILESTRING(1267e73c "WinIniBak",1267e76a "Desktop.WallPaper",120f3c0e "C:\\Users\\HP\\AppData\\Roaming\\Microsoft\\Windows\\Themes\\TranscodedWallpaper.jpg",126f0600 "scenes2.ini") ret=126f:0593 ds=1287`

The filename TranscodedWallpaper.jpg overruns the stack since the program only expects 8.3 filenames.

**Comment by anonimuos** [comment]
Ohh! So I guess there is no fix for this. I can workaround the error by temporarily setting the desktop background to a solid color or picture with short filename.

**Comment by anonimuos** [comment]
Fixed. Totally awesome!
