### ISSUE TITLE
Mission Chameleon - installer doesn't run

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#787]
The problem with the installer for this game is that it is 16 bit, but when I try to run it via WineVDM I get a message from this installer that some file is missing. Unfortunately, the installer does not specify which file it is. Is it possible to determine what file the installer might want? I am adding a link to this game (Note! I am only doing this so that you can download the game and test it on your own) - https://www.old-games.ru/game/3426.html

**Comment by cracyc** [comment]
Are you using the newest build?  When I run it the installer is fine until the end when it tries to run addhdr.exe which doesn't work because it's a dos program run from notice.exe, a win32 program.  Running the start menu shortcut fails because it's a win32 program missing some dlls that are in the winevdm windows/system dir.  Moving the dlls to the mission dir it crashes.  Running mission.exe directly fails with vntd.386 not loaded, not certain what can be done about that.

**Comment by MrPepka** [comment]
Yes, I have the latest build 0.7.0

**Comment by cracyc** [comment]
0.7.0 is very old.  Get https://ci.appveyor.com/api/buildjobs/n02ya3ap2l27akjv/artifacts/otvdm-master-1846.zip .

**Comment by MrPepka** [comment]
This build is the same. The file was not found and the game cannot be installed

**Comment by cracyc** [comment]
A trace should show what it's trying to do.

**Comment by MrPepka** [comment]
I am attaching the trace.txt file. In my opinion, nothing comes from it, although there is a location where the installer is probably looking for a missing file
[trace.txt](https://github.com/otya128/winevdm/files/5288236/trace.txt)

**Comment by cracyc** [comment]
To make a full trace see https://github.com/otya128/winevdm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md .  That's probably not necessary though because the problem is likely `055c:err:task:cwd_warning 619: could not get 8.3 filename. D:\Mission Chameleon\WINDOWS\system`.  Like ntvdm, winevdm needs 8.3 filenames to be able to open files.  Rename that directory to something 8.3 char long or use `fsutil file setshortname <Path> <Shortname>` to create one.

**Comment by MrPepka** [comment]
Thank you for your help. Only now has the game been installed
