### ISSUE TITLE
Total Mayhem - doesn't run with WineVDM

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#788]
I can't run this game via WineVDM. When I drag the game's exe file to the otvdm.exe file, I have a SEGV error, and when I run it via CMD, I have a message that the Language.001 file cannot be loaded. I am also unable to generate the trace.txt file despite the correct configuration of the environment. Of course I have the latest version of WineVDM
Link for game - https://www.old-games.ru/game/2059.html

**Comment by cracyc** [comment]
This does all kind of evil, using dpmi to run in v86 mode, calling the video bios directly, basically it's a dos program wrapped in a windows program and would be very difficult to make work and unlikely to ever happen (it doesn't work in ntvdm either).

**Comment by cracyc** [comment]
Despite the uglyness turns out it's fixable.  It uses scitechsoft windirect with their univbe drivers for video (which behaves somewhat like dispdib) and hmi sound operating system which accesses the sound adapter directly (wines soundblaster isn't good enough for this).  Thankfully the univbe can be disabled in settings.exe so it can use our vesa emulation directly and the sound falls back the waveout if it can't find a supported sound device.
