### ISSUE TITLE
NASCAR Revolution - installer doesn't run

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#802]
I am reporting another issue with WineVDM. Namely, I can't run the NASCAR Revolution game installer. Previously it worked, and on build 1860 when I start it, the installer hits 100% and I hear an error message sound (I can't see the message itself). I was able to see a SEGV error once and nothing else. Would you take a look at it? From what I can see, there is exactly the same error as in Burn: Cycle
[trace.txt](https://github.com/otya128/winevdm/files/5478351/trace.txt)

**Comment by cracyc** [comment]
I can't repo this.  You're doing something wrong with that trace because it's not running the program at all.  The command line current dir needs to be the directory that the program is in, in this case the cdrom drive.  Anyway, the only part of the installer that is 16bit is the launcher stub.  If an error occurs after the elevation message it would be an error from the 32bit part.

**Comment by MrPepka** [comment]
I solved the problem. It was enough to change the name of the folder where the installer is. Sorry for the confusion
