### ISSUE TITLE
Installation of otvdm doesn't work on Windows 10

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#942]
Hello,
I am not able to install otvdm on my Windows 10 system (64 Bit, 21H1). When I try to do so via the file install.lnk or install.inf, I get the following error message: "The inf file you selected does not suppport this method of installation".

(The screenshot shows the german messagebox)
![grafik](https://user-images.githubusercontent.com/68747203/114554076-9ed09880-9c66-11eb-9a00-34f1d23d2054.png)

**Comment by otya128** [comment]
I've tried several versions (build 19042, 21354) and it works fine.
The same error occurs on the 32-bit version of Windows 10, but it is unknown why the error occurs on the 64-bit version.
For the time being, you can install it by rewriting the install.reg file.
https://github.com/otya128/winevdm/blob/4f12c5f7e9ecb2a256e933f26f55db26f23e7b4f/install.reg

**Comment by LegacyFreak** [comment]
Hello,
installation via reg file works for me. Thanks for that advice.

**Comment by ldca58** [comment]
This problem is still not solved. I tried to install otvdm on Windows 10 Pro (22H2), but no matter which method I try (double clicking the Install shortcut or right-click on the .inf file and choosing install), I get this error: "The INF file you've selected does not
support this method of installation. The required section was not found in the INF."
![image](https://github.com/otya128/winevdm/assets/75849694/659e53b6-3a46-49a0-922a-d6b7fddc03d3)
