### ISSUE TITLE
MS Graph 5 extremely slow

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#973]
Hello,
MS Graph 5 ist extremly slow, especially whent it draws its dialogs on the sceen. While a dialog is drawn you 
can notice an enless sequence of calls of the functions GETPIXEL(), SETPIXEL() and PATBLT().
The attached trace contains this waiting for a dialog to be drawn at it's end. I closed Graph 5 via the otvdm console while the dialog was drawn. Maybe you have an explanation for this extrem ineffective behaviour. It would be nice, if you could implement some optimizitions here.

[Trace_Graph5.zip](https://github.com/otya128/winevdm/files/6410038/Trace_Graph5.zip)

**Comment by LegacyFreak** [comment]
Hello,
I did some further testing and found a solution. If I activate the option DWMDesktopDCFix in otvdm.ini Graph5 runs in normal speed. 
But there is another problem now. MS Access 2.0, which is for me the most useful container for MSGraph, does not start if this option ist set. I will create abother issue for the problem.. One solution here is to start the Access and the Graph processes with separate otvdm.ini configurations, but this is not really nice.
By the way, why is there an additional item in the taskbar of Windows 10 for every otvdm task that ist startet with the DWMDesktopDCFix  option? Seems to be a bug.

**Comment by cracyc** [comment]
DWMDesktopDCFix creates a new window that is substituted for the desktop window in GetDC calls.  That is the extra taskbar item.  Graph calls GetPixel(Desktophwnd,...) a lot when running which on Windows 10 is probably a very slow operation.  That would explain why it's so much faster with DWMDesktopDCFix and Access likely doesn't work because it wants the real desktop hwnd.
